export const GET_CART_LOADING = "GET_CART_LOADING";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";
export const GET_CART_RESET = "GET_CART_RESET";

export const GET_SELECTED_CART_LOADING = "GET_SELECTED_CART_LOADING";
export const GET_SELECTED_CART_SUCCESS = "GET_SELECTED_CART_SUCCESS";
export const GET_SELECTED_CART_ERROR = "GET_SELECTED_CART_ERROR";
export const GET_SELECTED_CART_RESET = "GET_SELECTED_CART_RESET";

export const ADD_CART_LOADING = "ADD_CART_LOADING";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_ERROR = "ADD_CART_ERROR";
export const ADD_CART_RESET = "ADD_CART_RESET";

export const REMOVE_CART_LOADING = "REMOVE_CART_LOADING";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_ERROR = "REMOVE_CART_ERROR";
export const REMOVE_CART_RESET = "REMOVE_CART_RESET";

export const UPDATE_CART_LOADING = "UPDATE_CART_LOADING";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_ERROR = "UPDATE_CART_ERROR";
export const UPDATE_CART_RESET = "UPDATE_CART_RESET";

export const EDIT_QTY_LOADING = "EDIT_QTY_LOADING";
export const EDIT_QTY_SUCCESS = "EDIT_QTY_SUCCESS";
export const EDIT_QTY_ERROR = "EDIT_QTY_ERROR";
export const EDIT_QTY_RESET = "EDIT_QTY_RESET";

export const SHIPPING_INFO_LOADING = "SHIPPING_INFO_LOADING";
export const SHIPPING_INFO_SUCCESS = "SHIPPING_INFO_SUCCESS";
export const SHIPPING_INFO_ERROR = "SHIPPING_INFO_ERROR";
export const SHIPPING_INFO_RESET = "SHIPPING_INFO_RESET";
