export const GET_CATEGORY_LOADING = "GET_CATEGORY_LOADING";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";
export const GET_CATEGORY_RESET = "GET_CATEGORY_RESET";

export const GET_CATEGORY_LIST_LOADING = "GET_CATEGORY_LIST_LOADING";
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS";
export const GET_CATEGORY_LIST_ERROR = "GET_CATEGORY_LIST_ERROR";
export const GET_CATEGORY_LIST_RESET = "GET_CATEGORY_LIST_RESET";

export const ADD_CATEGORY_LOADING = "ADD_CATEGORY_LOADING";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_ERROR = "ADD_CATEGORY_ERROR";
export const ADD_CATEGORY_RESET = "ADD_CATEGORY_RESET";

export const REMOVE_CATEGORY_LOADING = "REMOVE_CATEGORY_LOADING";
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS";
export const REMOVE_CATEGORY_ERROR = "REMOVE_CATEGORY_ERROR";
export const REMOVE_CATEGORY_RESET = "REMOVE_CATEGORY_RESET";

export const UPDATE_CATEGORY_LOADING = "UPDATE_CATEGORY_LOADING";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_ERROR = "UPDATE_CATEGORY_ERROR";
export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";
