export const CREATE_ORDER_LOADING = "CREATE_ORDER_LOADING";

export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";

export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const CREATE_ORDER_RESET = "CREATE_ORDER_RESET";

export const FETCH_ORDERS_LOADING = "FETCH_ORDERS_LOADING";

export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";

export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const FETCH_ORDER_LOADING = "FETCH_ORDER_LOADING";

export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";

export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";

export const ORDER_PAY_LOADING = "ORDER_PAY_LOADING";

export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";

export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";

export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_MARK_PAY_LOADING = "ORDER_MARK_PAY_LOADING";

export const ORDER_MARK_PAY_SUCCESS = "ORDER_MARK_PAY_SUCCESS";

export const ORDER_MARK_PAY_ERROR = "ORDER_MARK_PAY_ERROR";

export const ORDER_MARK_PAY_RESET = "ORDER_MARK_PAY_RESET";

export const ORDER_LIST_LOADING = "ORDER_LIST_LOADING";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_ERROR = "ORDER_LIST_ERROR";
export const ORDER_LIST_RESET = "ORDER_LIST_RESET";

export const ORDER_DELETE_LOADING = "ORDER_DELETE_LOADING";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_ERROR = "ORDER_DELETE_ERROR";
export const ORDER_DELETE_RESET = "ORDER_DELETE_RESET";

export const ORDER_DELIVER_LOADING = "ORDER_DELIVER_LOADING";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_ERROR = "ORDER_DELIVER_ERROR";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";
