export const PRODUCT_LIST_LOADING = "PRODUCT_LIST_LOADING";
export const PRODUCT_LIST_FETCHED = "PRODUCT_LIST_FETCHED";
export const PRODUCT_LIST_ERROR = "PRODUCT_LIST_ERROR";

export const FIRST_CATEGORY_LOADING = "FIRST_CATEGORY_LOADING";
export const FIRST_CATEGORY_SUCCESS = "FIRST_CATEGORY_SUCCESS";
export const FIRST_CATEGORY_ERROR = "FIRST_CATEGORY_ERROR";

export const SECOND_CATEGORY_LOADING = "SECOND_CATEGORY_LOADING";
export const SECOND_CATEGORY_SUCCESS = "SECOND_CATEGORY_SUCCESS";
export const SECOND_CATEGORY_ERROR = "SECOND_CATEGORY_ERROR";

export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_ERROR = "CATEGORY_ERROR";

export const PRODUCT_DETAILS_LOADING = "PRODUCT_DETAILS_LOADING";
export const PRODUCT_DETAILS_FETCHED = "PRODUCT_DETAILS_FETCHED";
export const PRODUCT_DETAILS_ERROR = "PRODUCT_DETAILS_ERROR";
export const PRODUCT_DETAILS_RESET = "PRODUCT_DETAILS_RESET";

export const PRODUCT_DELETE_LOADING = "PRODUCT_DELETE_LOADING";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR";
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET";

export const PRODUCT_CREATE_LOADING = "PRODUCT_CREATE_LOADING";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_ERROR = "PRODUCT_CREATE_ERROR";
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET";

export const PRODUCT_EDIT_LOADING = "PRODUCT_EDIT_LOADING";
export const PRODUCT_EDIT_SUCCESS = "PRODUCT_EDIT_SUCCESS";
export const PRODUCT_EDIT_ERROR = "PRODUCT_EDIT_ERROR";
export const PRODUCT_EDIT_RESET = "PRODUCT_EDIT_RESET";

export const PRODUCT_CREATE_REVIEW_LOADING = "PRODUCT_CREATE_REVIEW_LOADING";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_ERROR = "PRODUCT_CREATE_REVIEW_ERROR";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const PRODUCT_SEARCH_LOADING = "PRODUCT_SEARCH_LOADING";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_ERROR = "PRODUCT_SEARCH_ERROR";
export const PRODUCT_SEARCH_RESET = "PRODUCT_SEARCH_RESET";

export const PRODUCT_TOP_LOADING = "PRODUCT_TOP_LOADING";
export const PRODUCT_TOP_SUCCESS = "PRODUCT_TOP_SUCCESS";
export const PRODUCT_TOP_ERROR = "PRODUCT_TOP_ERROR";
