export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_FETCHED = "USER_LOGIN_FETCHED";
export const USER_LOGIN_FETCH_ERROR = "USER_LOGIN_FETCH_ERROR";

export const USER_REGISTER_LOADING = "USER_REGISTER_LOADING";
export const USER_REGISTER_FETCHED = "USER_REGISTER_FETCHED";
export const USER_REGISTER_FETCH_ERROR = "USER_REGISTER_FETCH_ERROR";

export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const USER_DETAILS_FETCHED = "USER_DETAILS_FETCHED";
export const USER_DETAILS_FETCH_ERROR = "USER_DETAILS_FETCH_ERROR";

export const USER_UPDATE_LOADING = "USER_UPDATE_LOADING";
export const USER_UPDATE_FETCHED = "USER_UPDATE_FETCHED";
export const USER_UPDATE_FETCH_ERROR = "USER_UPDATE_FETCH_ERROR";

export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USERS_LIST_LOADING = "USERS_LIST_LOADING";
export const USERS_LIST_FETCHED = "USERS_LIST_FETCHED";
export const USERS_LIST_FETCH_ERROR = "USERS_LIST_FETCH_ERROR";
export const USERS_LIST_RESET = "USERS_LIST_RESET";

export const USER_DELETE_LOADING = "USER_DELETE_LOADING";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_ERROR = "USER_DELETE_ERROR";
export const USER_DELETE_RESET = "USER_DELETE_RESET";

export const USER_DETAIL_LOADING = "USER_DETAIL_LOADING";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_ERROR = "USER_DETAIL_ERROR";
export const USER_DETAIL_RESET = "USER_DETAIL_RESET";

export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const USER_LOGOUT = "USER_LOGOUT";
